# -*- coding: utf-8 -*-
"""trading-sentiment-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q38BOOXLu-gTLMo89LTZzjeBx3WCRxpf

# Part A — Data preparation
"""



import os
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

os.chdir('/content/drive/MyDrive')

# Load datasets
fgi = pd.read_csv("/content/drive/MyDrive/fear_greed_index.csv")
hd = pd.read_csv("/content/drive/MyDrive/historical_data.csv")

"""## Dataset (Fear_Greed_Index)"""



fgi.info()

fgi.head()

fgi.describe(include="all")

print("fear gread index shape:", fgi.shape)

print("Missing values in fear gread index:")
print(fgi.isnull().sum())

print("Duplicate rows in fear gread index:", fgi.duplicated().sum())

plt.figure(figsize=(10, 6))
ax = sns.countplot(data=fgi, x='classification', hue='classification', palette='viridis', legend=False)

# Add counts on top of the bars
for p in ax.patches:
    ax.annotate(f'{int(p.get_height())}',
                (p.get_x() + p.get_width() / 2., p.get_height()),
                ha='center', va='center',
                xytext=(0, 5),
                textcoords='offset points')

plt.title('Distribution of Fear & Greed Index Classifications')
plt.xlabel('Classification')
plt.ylabel('Count')
plt.savefig('fear_greed_index_classification_distribution.png')
plt.show()

from sklearn.preprocessing import LabelEncoder

# Create encoder
le = LabelEncoder()


fgi['classification_encoded'] = le.fit_transform(fgi['classification'])

print(fgi[['classification', 'classification_encoded']])

mapping_df = pd.DataFrame({
    'Category': le.classes_,
    'Encoded': le.transform(le.classes_)
})

print(mapping_df)

fgi.info()

"""### Converting timestamps"""



fgi['date'] = pd.to_datetime(fgi['date'])
fgi['timestamp'] = pd.to_datetime(fgi['timestamp'])

fgi['date'] = fgi['date'].dt.date

"""## Dataset (Histroical_Data)"""

hd.info()

hd.head()

hd.describe(include="all")

hd.isnull().sum()

print(" histroical data shape:", hd.shape)

print("Missing values in histroical data:")
print(hd.isnull().sum())

print("Duplicate rows in histroical data:", hd.duplicated().sum())

hd.info()

"""### Convert timestamps"""

hd['Timestamp IST'] = pd.to_datetime(hd['Timestamp IST'], dayfirst=True)
hd['Timestamp'] = pd.to_datetime(hd['Timestamp'], unit='ms')

hd['date'] = hd['Timestamp'].dt.date

"""### Create the key metrics"""

daily_pnl = hd.groupby(['Account','date'])['Closed PnL'].sum()

hd['win'] = hd['Closed PnL'] > 0
win_rate = hd.groupby('Account')['win'].mean()

avg_trade_size = hd.groupby('Account')['Size USD'].mean()

trades_per_day = hd.groupby('date').size()

hd['Side'].value_counts(normalize=True)

"""### Merging Data"""

merged_data = pd.merge(hd,fgi,on='date',how='inner')

merged_data.info()

"""# Part B — Analysis

## Question 1
Does performance differ between Fear vs Greed?
"""

pnl_by_sentiment = merged_data.groupby('classification')['Closed PnL'].mean()
print(pnl_by_sentiment)

pnl_by_sentiment.plot(kind='bar')
plt.title("Average PnL by Sentiment")
plt.ylabel("PnL")
plt.savefig('average_pnl_by_sentiment.png')
plt.show()

win_rate = merged_data.groupby('classification')['win'].mean()
print(win_rate)

win_rate.plot(kind='bar')
plt.title("Win Rate by Sentiment")
plt.savefig('win_rate_by_sentiment.png')
plt.show()

drawdown = merged_data.groupby('classification')['Closed PnL'].min()
print(drawdown)

drawdown.plot(kind='bar')
plt.title("Worst Loss by Sentiment")
plt.savefig('worst_loss_by_sentiment.png')
plt.show()

"""## Question 2
Do traders change behavior based on sentiment?
"""

trades_count = merged_data.groupby('classification').size()
print(trades_count)

trades_count.plot(kind='bar')
plt.title("Trades by Sentiment")
plt.savefig('trades_by_sentiment.png')
plt.show()

position_size = merged_data.groupby('classification')['Size USD'].mean()
print(position_size)

position_size.plot(kind='bar')
plt.title("Position Size by Sentiment")
plt.savefig('position_size_by_sentiment.png')
plt.show()

long_short = pd.crosstab(
    merged_data['classification'],
    merged_data['Side'],
    normalize='index'
)

print(long_short)

long_short.plot(kind='bar', stacked=True)
plt.title("Long vs Short by Sentiment")
plt.savefig('long_short_by_sentiment.png')
plt.show()

"""## Question 3
Segments

### Segment 1 — Frequent vs Infrequent Traders
"""

trades_per_trader = merged_data.groupby('Account').size()

threshold = trades_per_trader.median()

merged_data['frequency'] = merged_data['Account'].map(
    lambda x: "Frequent" if trades_per_trader[x] > threshold else "Infrequent"
)

freq_perf = merged_data.groupby('frequency')['Closed PnL'].mean()
print(freq_perf)

freq_perf.plot(kind='bar')
plt.title("PnL: Frequent vs Infrequent")
plt.savefig('pnl_frequent_vs_infrequent.png')
plt.show()

"""### Segment 2 — High vs Low Trade Size"""

size_per_trader = merged_data.groupby('Account')['Size USD'].mean()
size_threshold = size_per_trader.median()

merged_data['size_group'] = merged_data['Account'].map(
    lambda x: "High Size" if size_per_trader[x] > size_threshold else "Low Size"
)

size_perf = merged_data.groupby('size_group')['Closed PnL'].mean()
print(size_perf)

"""### Segment 3 — Consistent Winners"""

win_rate_trader = merged_data.groupby('Account')['win'].mean()

merged_data['winner_group'] = merged_data['Account'].map(
    lambda x: "Consistent" if win_rate_trader[x] > 0.5 else "Inconsistent"
)

winner_perf = merged_data.groupby('winner_group')['Closed PnL'].mean()
print(winner_perf)

winner_perf.plot(kind='bar')
plt.title("PnL: Winners vs Others")
plt.savefig('pnl_winners_vs_others.png')
plt.show()

"""## Q4 Required Insights (Minimum 3)
Insight 1 — Sentiment Impacts Performance

Greed periods tend to produce higher profits and win rates compared to Fear periods.

Evidence:PnL chart,Win rate chart



Insight 2 — Sentiment Changes Behavior

Traders trade more frequently and use larger positions during Greed periods.

Evidence:Trade frequency chart,Position size chart



Insight 3 — Frequent Traders Perform Better

Frequent traders generally achieve higher PnL than infrequent traders.

Evidence:Segment chart
"""



"""# Part C — “Actionable output”

## Strategy 1 — Reduce Risk During Fear Days

Rule of Thumb:
During Fear sentiment days, traders should reduce position size and avoid high leverage.

Reasoning:

Fear days show higher losses (lower PnL)

Higher volatility increases drawdown risk

Large trades lose more during panic markets

Action:

Reduce position size by 30–50%

Avoid overtrading

Use tighter stop-loss
"""



"""## Strategy 2 — Limit Position Size for Inconsistent Traders

Rule of Thumb:
Inconsistent traders should use smaller position sizes.

Reasoning:

Inconsistent traders have lower win rates

Large trades increase losses

Risk management improves stability

Action:

Use smaller trades

Focus on consistency
"""

